# Generated by Django 5.2.12 on 2026-06-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_round_ratings_to_half'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='drink_preference',
            field=models.CharField(choices=[('alcohol', 'Alcohol'), ('non_alcohol', 'Non-alcoholic / Soft drinks')], default='non_alcohol', max_length=15),
        ),
    ]
