# Generated by Django 5.2.6 on 2025-10-12 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cric", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
