# Generated by Django 5.2.6 on 2025-10-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cric", "0002_alter_session_created_by"),
        ("cric", "add_created_by_to_session"),
    ]

    operations = []
