# Generated by Django 5.2.6 on 2025-10-12 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cric", "0003_merge_20251012_1444"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paid", models.BooleanField(default=False)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cric.session"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cric.team"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "user")},
            },
        ),
        migrations.AlterField(
            model_name="attendance",
            name="match_player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cric.sessionplayer"
            ),
        ),
        migrations.DeleteModel(
            name="MatchPlayer",
        ),
    ]
