# Generated by Django 5.2.12 on 2026-04-01 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cric', '0005_session_toss_result_alter_user_batting_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='guest_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
