# Generated by Django 5.2.12 on 2026-06-09 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cric_sessions', '0003_alter_sessionplayer_team'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_type', models.CharField(choices=[('alcohol', 'Alcohol'), ('non_alcohol', 'Non-alcoholic / Soft drinks')], max_length=15)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drink_rounds_paid', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drink_rounds_recorded', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drink_rounds', to='cric_sessions.session')),
            ],
            options={
                'unique_together': {('session', 'drink_type')},
            },
        ),
    ]
