# Generated by Django 5.2.4 on 2026-05-15 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cric_sessions', '0001_initial'),
        ('matches', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.payment'),
        ),
        migrations.AddField(
            model_name='session',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionplayer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cric_sessions.session'),
        ),
        migrations.AddField(
            model_name='sessionplayer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.team'),
        ),
        migrations.AddField(
            model_name='sessionplayer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='match_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cric_sessions.sessionplayer'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionplayer',
            unique_together={('session', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('match_player',)},
        ),
    ]
