# Generated by Django 5.2.4 on 2026-05-20 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cric_sessions', '0002_initial'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionplayer',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matches.team'),
        ),
    ]
