# Generated by Django 5.2.6 on 2026-05-29 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="overs_limit",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Innings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(default=1)),
                ("is_closed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batting_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batting_innings",
                        to="matches.team",
                    ),
                ),
                (
                    "bowling_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bowling_innings",
                        to="matches.team",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="innings",
                        to="matches.match",
                    ),
                ),
            ],
            options={
                "ordering": ["match", "number"],
                "unique_together": {("match", "number")},
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                (
                    "client_uuid",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("over_number", models.PositiveSmallIntegerField(default=0)),
                ("ball_in_over", models.PositiveSmallIntegerField(default=0)),
                ("runs_off_bat", models.PositiveSmallIntegerField(default=0)),
                (
                    "extra_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("wide", "Wide"),
                            ("noball", "No ball"),
                            ("bye", "Bye"),
                            ("legbye", "Leg bye"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("extra_runs", models.PositiveSmallIntegerField(default=0)),
                ("is_wicket", models.BooleanField(default=False)),
                (
                    "dismissal_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bowled", "Bowled"),
                            ("caught", "Caught"),
                            ("lbw", "LBW"),
                            ("runout", "Run out"),
                            ("stumped", "Stumped"),
                            ("hitwicket", "Hit wicket"),
                            ("other", "Other"),
                        ],
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bowler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="matches.player",
                    ),
                ),
                (
                    "fielder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="matches.player",
                    ),
                ),
                (
                    "non_striker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="matches.player",
                    ),
                ),
                (
                    "out_player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="matches.player",
                    ),
                ),
                (
                    "striker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="matches.player",
                    ),
                ),
                (
                    "innings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="matches.innings",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("innings", "sequence"), name="uniq_innings_sequence"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("client_uuid", ""), _negated=True),
                        fields=("innings", "client_uuid"),
                        name="uniq_innings_client_uuid",
                    ),
                ],
            },
        ),
    ]
