# Generated by Django 5.2.6 on 2026-05-29 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0002_match_overs_limit_innings_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="innings",
            name="current_bowler",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="matches.player",
            ),
        ),
        migrations.AddField(
            model_name="innings",
            name="current_non_striker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="matches.player",
            ),
        ),
        migrations.AddField(
            model_name="innings",
            name="current_striker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="matches.player",
            ),
        ),
    ]
