# Generated by Django 5.2.6 on 2026-05-29 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0003_innings_current_bowler_innings_current_non_striker_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="toss_decision",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="match",
            name="toss_winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="matches.team",
            ),
        ),
    ]
